### ISSUE TITLE
Error: Cannot find module 'bcrypt' -- also bcrypt install script fails with npm install

### ISSUE THREAD

**Issue by rocsteady** [thedjpetersen/subway#185]
ccheney@r0c:~/sandbox/subway/subway$ node subway 

module.js:340
    throw err;
    ^
Error: Cannot find module 'bcrypt'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/home/ccheney/sandbox/subway/subway/lib/socket.js:1:76)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)

ccheney@r0c:~/sandbox/subway/subway$ npm install bcrypt
npm http GET https://registry.npmjs.org/bcrypt
npm http 304 https://registry.npmjs.org/bcrypt
npm http GET https://registry.npmjs.org/bindings/1.0.0
npm http 304 https://registry.npmjs.org/bindings/1.0.0

> bcrypt@0.7.3 install /home/ccheney/sandbox/subway/subway/node_modules/bcrypt
> node-gyp rebuild

make: Entering directory `/home/ccheney/sandbox/subway/subway/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
In file included from /home/ccheney/.node-gyp/0.8.15/deps/openssl/openssl/include/openssl/e_os2.h:1:0,
                 from /home/ccheney/.node-gyp/0.8.15/deps/openssl/openssl/include/openssl/../../crypto/ossl_typ.h:58,
                 from /home/ccheney/.node-gyp/0.8.15/deps/openssl/openssl/include/openssl/ossl_typ.h:1,
                 from /home/ccheney/.node-gyp/0.8.15/deps/openssl/openssl/include/openssl/../../crypto/rand/rand.h:63,
                 from /home/ccheney/.node-gyp/0.8.15/deps/openssl/openssl/include/openssl/rand.h:1,
                 from ../src/bcrypt_node.cc:38:
/home/ccheney/.node-gyp/0.8.15/deps/openssl/openssl/include/openssl/../../e_os2.h:56:33: fatal error: openssl/opensslconf.h: No such file or directory
compilation terminated.
make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
make: Leaving directory`/home/ccheney/sandbox/subway/subway/node_modules/bcrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:236:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:99:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System Linux 3.5.0-19-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ccheney/sandbox/subway/subway/node_modules/bcrypt
gyp ERR! node -v v0.8.15
gyp ERR! node-gyp -v v0.7.1
gyp ERR! not ok 
npm ERR! bcrypt@0.7.3 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.7.3 install script.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.5.0-19-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "bcrypt"
npm ERR! cwd /home/ccheney/sandbox/subway/subway
npm ERR! node -v v0.8.15
npm ERR! npm -v 1.1.66
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ccheney/sandbox/subway/subway/npm-debug.log
npm ERR! not ok code 0

wat do?

**Comment by dileeptp** [comment]
Just download bcrypt-nodejs from this link  https://github.com/shaneGirish/bcrypt-nodejs .Rename the folder from bcrypt-nodejs to bcrypt and put it inside node_modules direcory. This solved my problem

**Comment by karthickyuva** [comment]
Hi https://github.com/dileeptp, its working fine for me. 

Thanks

**Comment by rituraj841** [comment]
Thanks dileeptp ..I had the same issue and this worked for me too..

**Comment by linux08** [comment]
Thanks dileeptp,it worked

**Comment by borellaster** [comment]
Thanks @dileeptp. Works fine for me too.

**Comment by eltel** [comment]
Thanks @dileeptp - Youre the man!

**Comment by thedjpetersen** [comment]
If people are still using this, I can also update the package dependencies. But I would highly encourage all of you to take a look at shout, which is actively maintained.

**Comment by dgw** [comment]
Shout hasn't seen any development in about a year. If you're looking to switch off of subway, look at the repo thelounge/lounge (a fork of shout) instead.

**Comment by santhoshrajmudulakar** [comment]
before npm install you can remove bcrypt version from package.json file and paste "*" like this. after do npm install. it will work.

**Comment by webPpei** [comment]
> 只需从此链接下载bcrypt-nodejs https://github.com/shaneGirish/bcrypt-nodejs。将文件夹从bcrypt-nodejs重命名为bcrypt并将其放在node_modules目录中。这解决了我的问题

its working fine for me, thanks

**Comment by yusufmsalh** [comment]
> Just download bcrypt-nodejs from this link https://github.com/shaneGirish/bcrypt-nodejs .Rename the folder from bcrypt-nodejs to bcrypt and put it inside node_modules direcory. This solved my problem

I love you mate ,thank you so much

**Comment by anilkumartudu** [comment]
for anyone who had no successful outcome after following the above solutions can downgrade their node version (in my case i downgraded to v8.4.0). To downgrade your node version follow the steps provided in the [link.](https://gist.github.com/anilkumartudu/09124e247e2d54b315e2dac596f2a9b7) Hope this help someone.

**Comment by dgw** [comment]
@anilkumartudu Rather than jump through hoops downgrading things to get this abandoned project running, it would be better in the long run to use something else. Maybe [The Lounge](https://github.com/thelounge/thelounge), which is called out in subway's readme.

**Comment by thedjpetersen** [comment]
@anilkumartudu @dgw has the correct suggestion. I haven't touched this in a few years and would not advise.
